name: reflexman
description: A sample command-line application.
version: 0.0.1
homepage: https://florian.ws
author: Florian <me@florian.ws>

environment:
  sdk: '>2.0.0'

dependencies:
  args: ^1.5.0
  dartis: ^0.3.0
